### ISSUE TITLE
Stampa Buono di scarico

### ISSUE THREAD

**Issue by patriziavillani** [consiglionazionaledellericerche/sigla-main#21]
Creazione stampa buono di scarico (indicazioni via mail)

**Comment by gifracr** [comment]
[
[buono scarico per vendita.pdf](https://github.com/consiglionazionaledellericerche/sigla-main/files/5161138/buono.scarico.per.vendita.pdf)
[Impostazione testate buoni.xlsx](https://github.com/consiglionazionaledellericerche/sigla-main/files/5161139/Impostazione.testate.buoni.xlsx)
[buono di carico.pdf](https://github.com/consiglionazionaledellericerche/sigla-main/files/5161140/buono.di.carico.pdf)
[buono di scarico.pdf](https://github.com/consiglionazionaledellericerche/sigla-main/files/5161141/buono.di.scarico.pdf)



](url)

**Comment by gifracr** [comment]
Fatte le modifiche al layout e rilasciate in produzione
