### ISSUE TITLE
Servizio per invio dati di pagamento al portale CNR

### ISSUE THREAD

**Issue by patriziavillani** [consiglionazionaledellericerche/sigla-main#22]
La pubblicazione dei pagamenti dell'Ente (obbligatoria) richiede la predisposizione di un servizio (file json) da Sigla, utilizzabile dal Portale CNR appunto per la pubblicazione

**Comment by gifracr** [comment]
Servizio rilasciato e reso disponibile per i test. Comunicato ad Andrea Pompili l'indirizzo e fatta l'abilitazione per l'utente app.portalecnr su formazione. La url da invocare è http://sigla-main.test.si.cnr.it/SIGLA/restapi/datiPagamenti?daData=01/01/2016&aData=31/03/2016 per i dati del primo trimestre 2016.
