### ISSUE TITLE
Stampa documenti generici

### ISSUE THREAD

**Issue by patriziavillani** [consiglionazionaledellericerche/sigla-main#23]
E' stata segnalata un'anomalia nella stampa documenti generici passivi (la scelta della tipologia di documento produce una stampa vuota). Questo perchè la tipologia sui documenti generici passivi è un campo null quindi sarà tolta la selezione di questo campo dalla stampa documenti generici passivi.
Nel controllo però è emerso che molti documenti generici attivi non hanno questo campo valorizzato (cosa che invece per quelli attivi dovrebbe sempre essere). Quest'ultimo punto resta da verificare

**Comment by gifracr** [comment]
Reso obbligatorio il campo tipo documento generico per i documenti generici di entrata. Valorizzati i vecchi documenti generici con il tipo generico.
