### ISSUE TITLE
Problema nel file publiccode.yml, chiave videos

### ISSUE THREAD

**Issue by libremente** [consiglionazionaledellericerche/sigla-main#3]
Buongiorno @mspasiano,

ho notato che c'è un problema nel file `publiccode.yml`. 
Infatti, il formato publiccode.yml prevede che i video siano ospitati su una piattaforma di video sharing che supporti lo standard oEmbed; le opzioni più popolari sono YouTube e Vimeo.
Si veda https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/schema.core.html?highlight=video#sezione-description per maggiori informazioni. 
Resto a disposizione, grazie!

**Comment by mspasiano** [comment]
Per ora ho rimosso il riferimento e inserito nella build il validatore:
https://github.com/consiglionazionaledellericerche/sigla-main/blob/edc14d8e51caa4bd7e14e47f6efa58da2f7be689/.gitlab-ci.yml#L154-L164
