### ISSUE TITLE
Segnalazioni su consultazioni Sigla (da vedere)

### ISSUE THREAD

**Issue by patriziavillani** [consiglionazionaledellericerche/sigla-main#33]
Richiesta pervenuta dall'helpdesk Sigla (n. 86147)
Buongiorno,
vorrei chiedervi se potete valutare la possibilità di creare una stampa excel simile a quella che riporto nel file in allegato.
Sarebbe molto utile per poter verificare agevolmente la situazione dei progetti filtrando per voce del piano economico e per CdR.
Cordiali saluti

Elisabetta Torrisi
0223699403

Elisabetta Torrisi (30-09-2019 10:21:06) :
Buongiorno,
vorrei proporre una stampa diversa, che riporta i dati relativi ad un solo esercizio per ciascuna riga. Forse per voi è più semplice da elaborare anche se poi chi la utilizza dovrebbe fare una tabella pivot per vedere i dati confrontabili.
Nello stesso file ho aggiunto il secondo foglio che riporta una disposizione dei dati diversa ed un terzo foglio con la pivot.
Saluti

Torrisi

**Comment by patriziavillani** [comment]
Aggiungiamo anche la richiesta della segnalazione n. 91566:

Avrei bisogno di esportare in in unica tabella xls i campi sotto riportati per rendicontazione progetti :
Area progettuale - Progetto - Responsabile del progetto - Gae - Voce - Tipo movimento contabile ( Variazione/impegno) - Anno - Numero impegno - Descrizione - Importo della Spesa -Es.Doc . - Num.doc. amm.- N. mandato -Beneficiario impegno- Denominazione

**Comment by patriziavillani** [comment]
Aggiungo anche la richiesta e l'esempio inviato via Mail da Giuliana Morelli:
Buonasera Sig.ra Patrizia, le indicazioni che lei mi ha suggerito sono quelle a cui mi interfaccio da sempre per inserire questi  dati  in tabelle excel creati da i miei colleghi per la rendicontazione dei progetti.
Questo copiare dati mi può portare a un rischio di errore allora per ovviare al problema ho provato anche a convertire il PDF della transazione in excel.
Questa operazione comporta un disallineamento delle celle e andare a formattare le celle è un lavoro elaborioso, dispendioso e porta con se un alto rischio di errore.
Su sigla ho provato a fare varie estrazioni in excel ma i dati estratti non mi portano a quello che mi occorre.
E' molto difficile tenere aggiornate  le numerose  tabelle dei progetti con i dati degli impegni e delle variazioni  che sono costantemente in divenire in modo da avere sempre situazioni precise.
Ecco il motivo della mia richiesta al servizio helpdesk Mi può aiutare a superare questi problemi?
Ringraziando Saluto
Giuliana Morelli
Mi è stato inviato un esempio (Esempio stampa Progetto Morelli) salvato nella cartella SIGLA

**Comment by gifracr** [comment]
Helpdesk 93881_: sarebbe possibile implementare la stampa excel in "Consuntivo----Consultazioni----Disponibilita' Competenza/Residuo----Istituo CDR-GAE", con il codice terzo del Responsabile del GAE e il codice del progetto?
Grazie mille per la disponibilità.
Alessandra La Greca

**Comment by gifracr** [comment]
94031: Cari colleghi, 
compatibilmente con i vs. carichi di lavoro, vi chiedo se è possibile prevedere nella stampa del piano economico anche la "data proroga".
Cordiali saluti.

**Comment by gifracr** [comment]
Chiusi Helpdesk 93881 e 94031.

**Comment by gifracr** [comment]
Chiuse le chiamate e rilasciate le consultazioni che sono:
- Impegni/GAE ce si trova in Documenti Contabili/Consultazioni/GAE;
- Movimentazione Piano Economico che si trova in Configurazione/Progetti di Ricerca/Consultazioni.
