### ISSUE TITLE
Modifica controllo P.I. - Gruppo IVA

### ISSUE THREAD

**Issue by patriziavillani** [consiglionazionaledellericerche/sigla-main#48]
Quando si inserisce un Gruppo IVA in anagrafica Sigla, può essere che la P.I. sia già presente su una anagrafica esistente e valida, quindi occorre non bloccare l'inserimento se:
Si sta inserendo un gruppo IVA;
Se esiste solo un'altra anagrafica, oltre al gruppo IVA, con la stessa Partita IVA

**Comment by gifracr** [comment]
Rilasciata la modifica
