### ISSUE TITLE
Cambio UO Coordinatrice sul progetto

### ISSUE THREAD

**Issue by patriziavillani** [consiglionazionaledellericerche/sigla-main#7]
Quando si chiede la modifica della UO Coordinatrice del progetto (per chiusura Sede, accorpamento ecc.) e si modifica la UO Coordinatrice (che probabilmente arriva anche dalla Intranet già modificata), in sigla si crea il problema degli allegati non più visibili sul progetto (perchè nel path indicato sul documentale c'è la UO)

**Comment by raffaelepagano** [comment]
La issue viene chiusa in quanto positivamente risolta con la commit del 1 Aprile 2020
