### ISSUE TITLE
elenco progetti istituto

### ISSUE THREAD

**Issue by backit** [consiglionazionaledellericerche/sigla-main#79]
Voglio ottenere una lista di tutti i progetti del mio istituto con uno script python.
Usando l'action ConsProgettiAction ottengo una lista di 1431 elementi ma provando a cercare qualche progetto a caso non ne trovo nessuno.
Questa la query:
`'{"activePage":0,"maxItemsPerPage":4999,"clauses":[ \
{"condition":"AND","fieldName":"unita_organizzativa.cd_unita_organizzativa","operator":"=","fieldValue":"114.000"} \
], \
"context":{"esercizio":2021,"cd_unita_organizzativa":"114.000","cd_cds":"114","cd_cdr":"114.000.000"}}'`
questi i progetti ricercati:
SAC.AD002.040
DFM.AD006.222
DFM.AD002.057
che ho provato a cercare su cd_porogetto

**Comment by mspasiano** [comment]
Ciao, mi sa che sbagli il fieldName di seguito un esempio:

**Comment by backit** [comment]
Forse non mi sono spiegato, io non voglio trovare un progetto, voglio trovare *tutti* i progetti ed infatti con la query di cui sopra trovo un elenco di progetti. Ma cercando nella lista di risultati ottenuta alcuni progetti campione, giusto per verifcia, non li trovo.
