### ISSUE TITLE
elenco progetti

### ISSUE THREAD

**Issue by backit** [consiglionazionaledellericerche/sigla-main#80]
Ricreo per essere più chiaro.
Voglio ottenere una lista di **tutti i progetti** del mio istituto con uno script python.
Usando l'action ConsProgettiAction ottengo una lista di 1431 elementi.
Provando a cercare **nei risultati della query** qualche progetto reale a caso per test, non ne trovo nessuno.
Questa la query:
'{"activePage":0,"maxItemsPerPage":4999,"clauses":[ \ {"condition":"AND","fieldName":"unita_organizzativa.cd_unita_organizzativa","operator":"=","fieldValue":"114.000"} \ ], \ "context":{"esercizio":2021,"cd_unita_organizzativa":"114.000","cd_cds":"114","cd_cdr":"114.000.000"}}'
questi i codici dei progetti ricercati per test nel field cd_progetto:
SAC.AD002.040
DFM.AD006.222
DFM.AD002.057

**Comment by mspasiano** [comment]
Ciao ho effettuato la modifica che andrà in produzione al prossimo rilascio di SIGLA

**Comment by backit** [comment]
E quando dovrebbe esere il prossimo rialscio di sigla?

Grazie

**Comment by gifracr** [comment]
È stato rilasciato ieri sera
