### ISSUE TITLE
Action che restituisce errore java

### ISSUE THREAD

**Issue by backit** [consiglionazionaledellericerche/sigla-main#81]
Questa action
https://contab.cnr.it/SIGLA/ConsDispCompResIstVoceAction.json
resituisce un errore java: "it.cnr.jada.comp.ComponentException"

per replicarebaste aprire l'url.

**Comment by gifracr** [comment]
Corretta anomalia nella get, il bp nell'init si aspettava lo usercontext che nella get non viene passato

**Comment by backit** [comment]
Al momento l'errore persiste, forse bisogna aspettare il rilascio?

**Comment by gifracr** [comment]
E' stata rilasciata il 01/07/2021
